# Generated by Django 4.1.1 on 2022-10-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='traits',
            field=models.ManyToManyField(null=True, related_name='traits', to='traits.trait'),
        ),
    ]
